/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.List;
import java.util.Random;
import java.util.UUID;

import javax.sound.sampled.SourceDataLine;

import org.example.utils.Request;
import org.example.types.Customer;
import org.example.types.Vehicle;

public class App {
    public static void main(String[] args) {
        System.out.println("Started!");
        try{
            /*/
            List<Customer> c = Request.getCustomers();
            UUID c_uuid = c.get(0).id;
            System.out.println("vehilce");
            List<Vehicle> v = Request.getVehicles();
            UUID v_uuid = v.get(0).id;
            System.out.println("target");
            int result = Request.setVehicleTarget(v_uuid, c_uuid);*/

            //NaiveShortestPath algo = new NaiveShortestPath();
            //WeightedShortestPath algo2 = new WeightedShortestPath();
            RandomPath algo2 = new RandomPath();
            while(true){
                Thread.sleep(1000);
                //algo.run();
                algo2.run();
            }

        }catch(Exception e){
            System.out.println(e);
        }
    }
}
